port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50050
  use_external_ip: true
  node_ip: 135.181.5.108
keys:
  HYDI_LIVEKIT_KEY_2026: HYDI_LIVEKIT_SECRET_SUPER_SECURE_KEY_2026!
logging:
  level: info
